#pragma once
// Auto-generated from ISO-3166 (lukes/ISO-3166-Countries-with-Regional-Codes). Do not edit by hand.
#include <stdint.h>

struct CountryEntry { uint8_t continent; const char* name; const char* cc; };

static const char* const CONTINENT_NAMES[] = {"Africa","Asia","Europe","N. America","S. America","Oceania"};
#define CONTINENT_COUNT 6

static const CountryEntry COUNTRIES[] = {
    {0, "Algeria", "DZ"},
    {0, "Angola", "AO"},
    {0, "Benin", "BJ"},
    {0, "Botswana", "BW"},
    {0, "British Indian Ocean Territory", "IO"},
    {0, "Burkina Faso", "BF"},
    {0, "Burundi", "BI"},
    {0, "Cabo Verde", "CV"},
    {0, "Cameroon", "CM"},
    {0, "Central African Republic", "CF"},
    {0, "Chad", "TD"},
    {0, "Comoros", "KM"},
    {0, "Congo", "CG"},
    {0, "Djibouti", "DJ"},
    {0, "DR Congo", "CD"},
    {0, "Egypt", "EG"},
    {0, "Equatorial Guinea", "GQ"},
    {0, "Eritrea", "ER"},
    {0, "Eswatini", "SZ"},
    {0, "Ethiopia", "ET"},
    {0, "Gabon", "GA"},
    {0, "Gambia", "GM"},
    {0, "Ghana", "GH"},
    {0, "Guinea", "GN"},
    {0, "Guinea-Bissau", "GW"},
    {0, "Ivory Coast", "CI"},
    {0, "Kenya", "KE"},
    {0, "Lesotho", "LS"},
    {0, "Liberia", "LR"},
    {0, "Libya", "LY"},
    {0, "Madagascar", "MG"},
    {0, "Malawi", "MW"},
    {0, "Mali", "ML"},
    {0, "Mauritania", "MR"},
    {0, "Mauritius", "MU"},
    {0, "Mayotte", "YT"},
    {0, "Morocco", "MA"},
    {0, "Mozambique", "MZ"},
    {0, "Namibia", "NA"},
    {0, "Niger", "NE"},
    {0, "Nigeria", "NG"},
    {0, "Reunion", "RE"},
    {0, "Rwanda", "RW"},
    {0, "Saint Helena", "SH"},
    {0, "Sao Tome and Principe", "ST"},
    {0, "Senegal", "SN"},
    {0, "Seychelles", "SC"},
    {0, "Sierra Leone", "SL"},
    {0, "Somalia", "SO"},
    {0, "South Africa", "ZA"},
    {0, "South Sudan", "SS"},
    {0, "Sudan", "SD"},
    {0, "Tanzania", "TZ"},
    {0, "Togo", "TG"},
    {0, "Tunisia", "TN"},
    {0, "Uganda", "UG"},
    {0, "Western Sahara", "EH"},
    {0, "Zambia", "ZM"},
    {0, "Zimbabwe", "ZW"},
    {1, "Afghanistan", "AF"},
    {1, "Armenia", "AM"},
    {1, "Azerbaijan", "AZ"},
    {1, "Bahrain", "BH"},
    {1, "Bangladesh", "BD"},
    {1, "Bhutan", "BT"},
    {1, "Brunei", "BN"},
    {1, "Cambodia", "KH"},
    {1, "China", "CN"},
    {1, "Cyprus", "CY"},
    {1, "Georgia", "GE"},
    {1, "Hong Kong", "HK"},
    {1, "India", "IN"},
    {1, "Indonesia", "ID"},
    {1, "Iran", "IR"},
    {1, "Iraq", "IQ"},
    {1, "Israel", "IL"},
    {1, "Japan", "JP"},
    {1, "Jordan", "JO"},
    {1, "Kazakhstan", "KZ"},
    {1, "Korea", "KP"},
    {1, "Kuwait", "KW"},
    {1, "Kyrgyzstan", "KG"},
    {1, "Lao People's Democratic Republic", "LA"},
    {1, "Lebanon", "LB"},
    {1, "Macau", "MO"},
    {1, "Malaysia", "MY"},
    {1, "Maldives", "MV"},
    {1, "Mongolia", "MN"},
    {1, "Myanmar", "MM"},
    {1, "Nepal", "NP"},
    {1, "Oman", "OM"},
    {1, "Pakistan", "PK"},
    {1, "Palestine", "PS"},
    {1, "Philippines", "PH"},
    {1, "Qatar", "QA"},
    {1, "Saudi Arabia", "SA"},
    {1, "Singapore", "SG"},
    {1, "South Korea", "KR"},
    {1, "Sri Lanka", "LK"},
    {1, "Syria", "SY"},
    {1, "Tajikistan", "TJ"},
    {1, "Thailand", "TH"},
    {1, "Timor-Leste", "TL"},
    {1, "Turkey", "TR"},
    {1, "Turkmenistan", "TM"},
    {1, "United Arab Emirates", "AE"},
    {1, "Uzbekistan", "UZ"},
    {1, "Vietnam", "VN"},
    {1, "Yemen", "YE"},
    {2, "Aland Islands", "AX"},
    {2, "Albania", "AL"},
    {2, "Andorra", "AD"},
    {2, "Austria", "AT"},
    {2, "Belarus", "BY"},
    {2, "Belgium", "BE"},
    {2, "Bosnia and Herzegovina", "BA"},
    {2, "Bulgaria", "BG"},
    {2, "Croatia", "HR"},
    {2, "Czechia", "CZ"},
    {2, "Denmark", "DK"},
    {2, "Estonia", "EE"},
    {2, "Faroe Islands", "FO"},
    {2, "Finland", "FI"},
    {2, "France", "FR"},
    {2, "Germany", "DE"},
    {2, "Gibraltar", "GI"},
    {2, "Greece", "GR"},
    {2, "Guernsey", "GG"},
    {2, "Hungary", "HU"},
    {2, "Iceland", "IS"},
    {2, "Ireland", "IE"},
    {2, "Isle of Man", "IM"},
    {2, "Italy", "IT"},
    {2, "Jersey", "JE"},
    {2, "Latvia", "LV"},
    {2, "Liechtenstein", "LI"},
    {2, "Lithuania", "LT"},
    {2, "Luxembourg", "LU"},
    {2, "Malta", "MT"},
    {2, "Moldova", "MD"},
    {2, "Monaco", "MC"},
    {2, "Montenegro", "ME"},
    {2, "Netherlands", "NL"},
    {2, "North Macedonia", "MK"},
    {2, "Norway", "NO"},
    {2, "Poland", "PL"},
    {2, "Portugal", "PT"},
    {2, "Romania", "RO"},
    {2, "Russia", "RU"},
    {2, "San Marino", "SM"},
    {2, "Serbia", "RS"},
    {2, "Slovakia", "SK"},
    {2, "Slovenia", "SI"},
    {2, "Spain", "ES"},
    {2, "Svalbard", "SJ"},
    {2, "Sweden", "SE"},
    {2, "Switzerland", "CH"},
    {2, "Ukraine", "UA"},
    {2, "United Kingdom", "GB"},
    {2, "Vatican City", "VA"},
    {3, "Anguilla", "AI"},
    {3, "Antigua and Barbuda", "AG"},
    {3, "Aruba", "AW"},
    {3, "Bahamas", "BS"},
    {3, "Barbados", "BB"},
    {3, "Belize", "BZ"},
    {3, "Bermuda", "BM"},
    {3, "Bonaire", "BQ"},
    {3, "British Virgin Islands", "VG"},
    {3, "Canada", "CA"},
    {3, "Cayman Islands", "KY"},
    {3, "Costa Rica", "CR"},
    {3, "Cuba", "CU"},
    {3, "Curacao", "CW"},
    {3, "Dominica", "DM"},
    {3, "Dominican Republic", "DO"},
    {3, "El Salvador", "SV"},
    {3, "Greenland", "GL"},
    {3, "Grenada", "GD"},
    {3, "Guadeloupe", "GP"},
    {3, "Guatemala", "GT"},
    {3, "Haiti", "HT"},
    {3, "Honduras", "HN"},
    {3, "Jamaica", "JM"},
    {3, "Martinique", "MQ"},
    {3, "Mexico", "MX"},
    {3, "Montserrat", "MS"},
    {3, "Nicaragua", "NI"},
    {3, "Panama", "PA"},
    {3, "Puerto Rico", "PR"},
    {3, "Saint Barthelemy", "BL"},
    {3, "Saint Kitts and Nevis", "KN"},
    {3, "Saint Lucia", "LC"},
    {3, "Saint Martin", "MF"},
    {3, "Saint Pierre and Miquelon", "PM"},
    {3, "Saint Vincent and the Grenadines", "VC"},
    {3, "Sint Maarten", "SX"},
    {3, "Trinidad and Tobago", "TT"},
    {3, "Turks and Caicos Islands", "TC"},
    {3, "United States", "US"},
    {3, "US Virgin Islands", "VI"},
    {4, "Argentina", "AR"},
    {4, "Bolivia", "BO"},
    {4, "Brazil", "BR"},
    {4, "Chile", "CL"},
    {4, "Colombia", "CO"},
    {4, "Ecuador", "EC"},
    {4, "Falkland Islands", "FK"},
    {4, "French Guiana", "GF"},
    {4, "Guyana", "GY"},
    {4, "Paraguay", "PY"},
    {4, "Peru", "PE"},
    {4, "South Georgia", "GS"},
    {4, "Suriname", "SR"},
    {4, "Uruguay", "UY"},
    {4, "Venezuela", "VE"},
    {5, "American Samoa", "AS"},
    {5, "Australia", "AU"},
    {5, "Christmas Island", "CX"},
    {5, "Cocos", "CC"},
    {5, "Cook Islands", "CK"},
    {5, "Fiji", "FJ"},
    {5, "French Polynesia", "PF"},
    {5, "Guam", "GU"},
    {5, "Kiribati", "KI"},
    {5, "Marshall Islands", "MH"},
    {5, "Micronesia", "FM"},
    {5, "Nauru", "NR"},
    {5, "New Caledonia", "NC"},
    {5, "New Zealand", "NZ"},
    {5, "Niue", "NU"},
    {5, "Norfolk Island", "NF"},
    {5, "Northern Mariana Islands", "MP"},
    {5, "Palau", "PW"},
    {5, "Papua New Guinea", "PG"},
    {5, "Pitcairn", "PN"},
    {5, "Samoa", "WS"},
    {5, "Solomon Islands", "SB"},
    {5, "Tokelau", "TK"},
    {5, "Tonga", "TO"},
    {5, "Tuvalu", "TV"},
    {5, "Vanuatu", "VU"},
    {5, "Wallis and Futuna", "WF"},
};
#define COUNTRY_COUNT (sizeof(COUNTRIES)/sizeof(COUNTRIES[0]))
